spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/identity?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 9090

# Custom configuration
security:
  permit-all:
    - /v1/api/auth/login
    - /v1/api/auth/refresh-token
    - /swagger-ui/**
    - /v3/api-docs/**
jwt:
  privateKey: |  
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCWWyyBYFzi8xkY
    tqNCzw6T5f/FfYAf0c8vuJN+3YLZr+oiz9l3oO0sUCkaWoCqIq12MQImEBEIoNVq
    DDrRNOtKkq0tbw3vz2cmC7mqQAnV766TXgjP1fIIet5KphzsOlHEMUOSiXMy5ZFO
    dPK+Bwaxoa2CI7t8Eo0hoEZRAPZc79Qz78yW7JCB+dnH0/V3nBCiOK2BNXBZvoXQ
    2avmmNkEjqNN2NNyuxLNICZ7bvDkC+jy/6Bcx/QwcJ5yx6HPs7UXBljG7RF8x3fF
    nUTWkpbYYZ08ewjVDuRHAOMFUJCNoc47IkA+G4MgNenvHrVHs4/MsRDxNOBvw/Pe
    iXqn/mZzAgMBAAECggEAQvKTzYOXuGHf8dYYub2yUv5dNZVdAE4Of8QiwKFnCwC+
    MwPzY8Xe9RU4SAi2M4s/S1olB8etnfbnL9IEOnTis5C91XYWcYoa9qDP6dObzYts
    YyfCqrArlcUHx5tRU4ngMIhy+wOCrM31NkbyctR0EZHYzRKV/3fPKYLQ7G6OQ/DD
    Ahe7rwBmqJA9I8yVQUzBbHIvRaxifaqruLtX4WgTbyPw+wtz92oV2VG4R1JbkIhO
    XD6/h/4rnuwaZueDXm2rH138mEPBr9Ayybbjijhf0t9IkHBe9B8sFzxEBUtTKNZZ
    9Cg6+qKAgZ90R+TXw4v+PdEx/aO/T0ydqa/KhuvoSQKBgQDHWBzF3+aTd4PQcuwv
    bo1pz7d1tilNpkxTtFSceq/mie3mdjcW4NW0NSnSZNq5vnN+Yyo8Y1wns6mtkhct
    ldEMiBTelTXDiAijSAlBWrfme3ASx2JrjJtKti904akmV4+/D1SgjQwX9BEdNJkU
    AbUGRa41vmWBZubPoyxvg4HNDQKBgQDBFsnuRrIAFdlfsynA6b81Em1S2Y1JqSC4
    E+m9m7jmWCN6ZaJBDLKXDU+357V7pWYs2VKW7d6w8J2ybr+cbrlMaIIvfcg8i7WW
    Q/8De5v/dO1wqu+CnjjxXpBuGWm85wpXS/92B9h7X/BbSLhAkSu6WZBmF2Wxs1sO
    7cXFjxchfwKBgAKsdN5WjXIm5Tazg+Vy9ySXK5/BjLZE57srrQLYRmmyKeWwaja9
    V0BughwXTDO3kTb9v4BF2OOTblAsqHDtFHu1i4ocuDbiKTN/cNhWjibiOvOVhwVo
    QmDzJpnLuQgRnpTycLEikynzFROuM+tnxnTKFHcWEah1p9zbFGp+egw1AoGAPoIC
    HQEF3sEz/acifTEulR/CBHApLQ9zaCQKJzeiQ++EjLsaK7TQm9XTWNXKCp0g1qQD
    +JhI3z8Fzh3MKfguRG4Qtw8hI3iW8G5Sv+3kMm7H7xFnOAHArWLPntTbRiwFTP1t
    Veh0THxicyq3ey+D2G/mLyaj5UMK12ph+/K2qkECgYBi8JzQqa1YZaG94Deqz1D+
    6fGgeNYZmEr1Dzzw4fq6rZ8czEXaKa6w9+kdXJ55k+CyTbh9kVAWIe/wbPx6wuwe
    V69ST7qDiEqcwviY+z3yniVUd9oUF79pLW3oRyn05Cn4dIMOWK/wduW3T8YUpA05
    86wTtsXQzHGfSqjptN9Qqw==
    -----END PRIVATE KEY-----
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAllssgWBc4vMZGLajQs8O
    k+X/xX2AH9HPL7iTft2C2a/qIs/Zd6DtLFApGlqAqiKtdjECJhARCKDVagw60TTr
    SpKtLW8N789nJgu5qkAJ1e+uk14Iz9XyCHreSqYc7DpRxDFDkolzMuWRTnTyvgcG
    saGtgiO7fBKNIaBGUQD2XO/UM+/MluyQgfnZx9P1d5wQojitgTVwWb6F0Nmr5pjZ
    BI6jTdjTcrsSzSAme27w5Avo8v+gXMf0MHCecsehz7O1FwZYxu0RfMd3xZ1E1pKW
    2GGdPHsI1Q7kRwDjBVCQjaHOOyJAPhuDIDXp7x61R7OPzLEQ8TTgb8Pz3ol6p/5m
    cwIDAQAB
    -----END PUBLIC KEY-----
  jwtRefreshExpirationS: 604800
  jwtAccessTokenExpirationS: 86400
  issuer: CoreJavaHSTM
aes:
  secret-key: AnhLongDecorSecretKey0201
logging:
  level:
    org.springframework.security: DEBUG
    java_learn.identity: DEBUG
